### ISSUE TITLE
Tracking: Flutter Group Chat

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-flutter#112]
### Group Chat Alpha - [Targeting February 1, 2024]

- [ ] Reproduce utility classes/methods
  - [ ] Client
    - [x] create `libxmtp` `Client` alongside existing client creation
    - [x] properly `register_identity` with signature when necessary
    - [ ] expose logging from `libxmtp`
    - [x] include `installation_id` on `Client`
    - [ ] expose listing of installations
    - [ ] expose revoking of installations
  - [ ] Groups
    - [x] create a new group
    - [x] list groups (in isolation) - `listGroups()`
    - [ ] list groups (with other conversations) - `listConversations(includeGroups: true)`
    - [ ] stream groups (in isolation) - `streamGroups()`
    - [ ] stream groups (with other conversations) - `streamConversations(includeGroups: true)`
    - [x] `sync` database to propagate updates
  - [ ] Conversation/Group methods
    - [ ] Should have a unique identifier of the conversation `id()` equivalent to existing topic
    - [ ] Should be able to `send()` messages of any content type
    - [ ] Should be able to resync the libxmtp database `sync()`
    - [ ] Should be able to list messages `find_messages()` as Decoded and Decrypted Messages
    - [ ] Should be able to list members `list_members()`
    - [ ] Should be able to add members `add_members()`
    - [ ] Should be able to remove members `remove_members()`
    - [ ] Should be able to stream messages `stream()`
    - [ ] Should be able to leave a group `leave()`
    - [ ] Can check if a message can be sent `can_message()`
- [ ] Publish repo README covering Dev Preview features and with Dev Preview badge

### GA - [Targeting March 30, 2024]

 - [ ] Integrated with a third party app
    - [ ] Successfully received push notifications
 - [ ] Publish repo README with GA badge
 - [ ] Reference docs for SDK GA

### Nice to have

- [ ] Create sample app
    - [ ] Use SDK to demonstrate
        - [ ] Initialize client
        - [ ] List conversations
        - [ ] List messages
        - [ ] Send messages
        - [ ] Stream conversations
        - [ ] Stream messages
        - [ ] Wallet Connect
        - [ ] Group Chat
          - [ ] send messages (any content type)
          - [ ] add member
          - [ ] remove member
          - [ ] list members
          - [ ] leave

**Comment by tuddman** [comment]
Closing.  Per https://github.com/xmtp/libxmtp/pull/555 deprecating Flutter support.
