### ISSUE TITLE
Tracking: Flutter SDK v1.0

### ISSUE THREAD

**Issue by elisealix22** [xmtp/xmtp-flutter#4]
### Requirements

Port `xmtp-js` to `xmtp-flutter` and demonstrate core functionality in a Flutter sample app.

### Developer Preview - [Shipped December 22, 2022]

- [x] Setup XMTP as a [verified publisher](https://dart.dev/tools/pub/publishing#verified-publisher)
- [x] Create dart package: `xmtp_proto`
    - [x] Add a dart-package generator to https://github.com/xmtp/proto   
    - [x] Publish to https://pub.dev/packages/xmtp_proto
- [x] Create dart package: `xmtp-flutter`
    - [x] Set up work repo: https://github.com/xmtp/xmtp-flutter
    - [x] Wrap xmtp in a dart-conventional `xmtp.Client` (like `xmtp-js`)
    - [x] Add authentication to match xmtp-js
    - [x] Reproduce utility classes/methods:
        - [x] Client
        - [x] ConversationV1
        - [x] ConversationV2
        - [x] Conversations
        - [x] MessageV1
        - [x] MessageV2
        - [x] PrivateKey
        - [x] PublicKey
        - [x] PrivateKeyBundleV1
        - [x] PrivateKeyBundleV2
        - [x] PublicKeyBundle
        - [x] SignedPublicKeyBundle
        - [x] Stream
        - [x] TextCodec
        - [x] CompositeCodec
    - [x] Publish to https://pub.dev/packages/xmtp

### GA - [Target March 1, 2023]

 - [ ] Integrated with a third party app
    - [ ] Successfully received push notifications
 - [ ] Publish repo README with GA badge
 - [ ] Reference docs for SDK GA: https://github.com/xmtp/xmtp-flutter/issues/40

### Nice to have

- [x] Create sample app: xmtp/example-chat-flutter
    - [x] Use `xmtp-flutter` to demonstrate SDK (like `example-chat-react`)
        - [ ] Initialize client
        - [x] List messages
        - [x] Send messages
        - [x] Stream messages
  
### Decision Log
- Dec 5, 2022: We are **not** planning on including `conversations.streamAllMessages()` in the Flutter SDK for now as we believe between push notifications & periodic polling it will be less useful than it was on web.
- Jan 18, 2023: We are targeting EthDenver for our SDK GA

**Comment by elisealix22** [comment]
Closing this since v1.0 is live!
